name: conta
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  get_it: ^7.7.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3
  flutter_map: ^7.0.2
  local_auth: ^2.2.0
  fl_chart: ^0.69.0
  intl: ^0.19.0
  mobile_scanner: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


  assets: 
    - assets/images/bgimg1.png
    - assets/images/success_animate.gif
    - assets/images/room-banner.png
    - assets/images/avatars/baleia.png
    - assets/images/avatars/camarao.png
    - assets/images/avatars/caracol.png
    - assets/images/avatars/cavalo-marinho.png
    - assets/images/avatars/gato.png
    - assets/images/avatars/homem1.png
    - assets/images/avatars/mulher1.png
    - assets/images/avatars/mulher2.png
    - assets/images/avatars/mulher3.png
    - assets/images/avatars/passaro.png
    - assets/images/avatars/pato.png
    - assets/images/avatars/porco.png
    - assets/images/avatars/rato.png
    - assets/images/avatars/zebra.png
  
